language: go
sudo: required
go:
  - 1.7

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get -qq update
  - sudo apt-get install gcc-4.8 g++-4.8 -y --force-yes

install:
  - go get -u github.com/whyrusleeping/gx
  - go get -u github.com/whyrusleeping/gx-go
  - gx install
  - gx-go rewrite && go get -tags=embed ./...
  - ./install.sh

script: gx-go rewrite && go test ./mc/...

# don't cache our source dir
before_cache:
  - rm -rf $GOPATH/src/github.com/mediachain/concat

# cache go dependencies (espeically /pkg with compiled gorocksdb)
cache:
  directories:
    - $GOPATH/src
    - $GOPATH/pkg
